import type { Metadata } from "next";
import { Inter, Libre_Caslon_Text } from "next/font/google";
import "../globals.css";
import { Footer, Header } from "@/sections";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import {setRequestLocale} from "next-intl/server";
import {hasLocale} from "use-intl";
import {routing} from "@/i18n/routing";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const libreCaslon = Libre_Caslon_Text({
  variable: "--font-libre",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({locale}));
}

export default async function LocaleLayout({
  children,
  params
}: LayoutProps<'/[locale]'>) {
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = (await import(`../../translations/${locale}.json`)).default;

  setRequestLocale(locale);

  return (
    <html lang={locale}>
    <body className={`${inter.variable} ${libreCaslon.variable} antialiased`}>
    <NextIntlClientProvider locale={locale} messages={messages}>
      <Header />
      {children}
      <Footer locale={locale} />
    </NextIntlClientProvider>
    </body>
    </html>
  );
}
