import type { Metadata } from "next";
import { Inter, Libre_Caslon_Text } from "next/font/google";
import "../globals.css";
import { Footer, Header } from "@/sections";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const libreCaslon = Libre_Caslon_Text({
  variable: "--font-libre",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
 children,
 params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const selectedLocale = locale || "uk";
  console.log({ selectedLocale })
  let translations;
  try {
    translations = (await import(`../../translations/${selectedLocale}.json`)).default;
    console.log({ translations })
  } catch (error) {
    console.log({ error })
    notFound();
  }

  return (
    <html lang={selectedLocale}>
    <body className={`${inter.variable} ${libreCaslon.variable} antialiased`}>
    <NextIntlClientProvider locale={locale} messages={translations}>
      <Header />
      {children}
      <Footer />
    </NextIntlClientProvider>
    </body>
    </html>
  );
}
